import type { LinkdingBookmark, LinkdingResponse, LinkdingAsset, LinkdingAssetResponse } from '../types';

export const mockBookmarks: LinkdingBookmark[] = [
  {
    id: 1,
    url: 'https://example.com/lorem-ipsum-dolor-sit-amet',
    title: 'Lorem Ipsum: A Comprehensive Guide',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    notes: '',
    website_title: 'Lorem Ipsum Today',
    website_description: 'Your source for classical Latin text and typographical wisdom',
    web_archive_snapshot_url: 'https://web.archive.org/web/20240101000000/https://example.com/lorem-ipsum-dolor-sit-amet',
    favicon_url: 'https://example.com/favicon.ico',
    preview_image_url: 'https://example.com/preview1.jpg',
    is_archived: false,
    unread: true,
    shared: false,
    tag_names: ['lorem', 'ipsum', 'design', 'typography'],
    date_added: '2024-01-01T10:00:00Z',
    date_modified: '2024-01-01T10:00:00Z',
  },
  {
    id: 2,
    url: 'https://example.com/consectetur-adipiscing-elit',
    title: 'Consectetur Adipiscing: Modern Typography Trends',
    description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    notes: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    website_title: 'Design Weekly',
    website_description: 'Weekly insights into design and typography',
    web_archive_snapshot_url: 'https://web.archive.org/web/20240102000000/https://example.com/consectetur-adipiscing-elit',
    favicon_url: 'https://example.com/favicon2.ico',
    preview_image_url: 'https://example.com/preview2.jpg',
    is_archived: false,
    unread: false,
    shared: true,
    tag_names: ['design', 'typography', 'modern'],
    date_added: '2024-01-02T11:30:00Z',
    date_modified: '2024-01-02T11:30:00Z',
  },
  {
    id: 3,
    url: 'https://example.com/sed-do-eiusmod-tempor',
    title: 'Sed Do Eiusmod: The History of Placeholder Text',
    description: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    notes: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.',
    website_title: 'History of Text',
    website_description: 'Exploring the origins of textual conventions',
    web_archive_snapshot_url: '',
    favicon_url: 'https://example.com/favicon3.ico',
    preview_image_url: '',
    is_archived: true,
    unread: false,
    shared: false,
    tag_names: ['history', 'text', 'placeholder'],
    date_added: '2024-01-03T14:15:00Z',
    date_modified: '2024-01-03T14:15:00Z',
  },
  {
    id: 4,
    url: 'https://example.com/incididunt-ut-labore',
    title: 'Incididunt Ut Labore: Working with Lorem Ipsum',
    description: 'Totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',
    notes: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.',
    website_title: 'Developer Resources',
    website_description: 'Tools and resources for developers',
    web_archive_snapshot_url: 'https://web.archive.org/web/20240104000000/https://example.com/incididunt-ut-labore',
    favicon_url: 'https://example.com/favicon4.ico',
    preview_image_url: 'https://example.com/preview4.jpg',
    is_archived: false,
    unread: true,
    shared: false,
    tag_names: ['development', 'tools', 'lorem'],
    date_added: '2024-01-04T09:45:00Z',
    date_modified: '2024-01-04T09:45:00Z',
  },
  {
    id: 5,
    url: 'https://example.com/dolore-magna-aliqua',
    title: 'Dolore Magna Aliqua: Best Practices for Placeholder Text',
    description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.',
    notes: 'Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',
    website_title: 'Best Practices Hub',
    website_description: 'Industry best practices and guidelines',
    web_archive_snapshot_url: '',
    favicon_url: 'https://example.com/favicon5.ico',
    preview_image_url: 'https://example.com/preview5.jpg',
    is_archived: false,
    unread: false,
    shared: true,
    tag_names: ['best-practices', 'guidelines', 'text'],
    date_added: '2024-01-05T16:20:00Z',
    date_modified: '2024-01-05T16:20:00Z',
  },
  {
    id: 6,
    url: 'https://example.com/ut-enim-ad-minim',
    title: 'Ut Enim Ad Minim: Understanding Classical Latin',
    description: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.',
    notes: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam.',
    website_title: 'Classical Studies',
    website_description: 'Exploring ancient languages and literature',
    web_archive_snapshot_url: 'https://web.archive.org/web/20240106000000/https://example.com/ut-enim-ad-minim',
    favicon_url: 'https://example.com/favicon6.ico',
    preview_image_url: '',
    is_archived: true,
    unread: false,
    shared: false,
    tag_names: ['latin', 'classical', 'language'],
    date_added: '2024-01-06T13:10:00Z',
    date_modified: '2024-01-06T13:10:00Z',
  },
  {
    id: 7,
    url: 'https://example.com/quis-nostrud-exercitation',
    title: 'Quis Nostrud Exercitation: Lorem Ipsum in Modern Design',
    description: 'Nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.',
    notes: 'Eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim.',
    website_title: 'Modern Design Trends',
    website_description: 'Current trends in design and user experience',
    web_archive_snapshot_url: '',
    favicon_url: 'https://example.com/favicon7.ico',
    preview_image_url: 'https://example.com/preview7.jpg',
    is_archived: false,
    unread: true,
    shared: false,
    tag_names: ['design', 'modern', 'ux'],
    date_added: '2024-01-07T08:30:00Z',
    date_modified: '2024-01-07T08:30:00Z',
  },
  {
    id: 8,
    url: 'https://example.com/ullamco-laboris-nisi',
    title: 'Ullamco Laboris Nisi: The Art of Typography',
    description: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti.',
    notes: 'Quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.',
    website_title: 'Typography Masters',
    website_description: 'Master the art of beautiful typography',
    web_archive_snapshot_url: 'https://web.archive.org/web/20240108000000/https://example.com/ullamco-laboris-nisi',
    favicon_url: 'https://example.com/favicon8.ico',
    preview_image_url: 'https://example.com/preview8.jpg',
    is_archived: false,
    unread: false,
    shared: true,
    tag_names: ['typography', 'art', 'design'],
    date_added: '2024-01-08T12:45:00Z',
    date_modified: '2024-01-08T12:45:00Z',
  },
];

export const mockArchivedBookmarks: LinkdingBookmark[] = mockBookmarks.filter(bookmark => bookmark.is_archived);
export const mockUnreadBookmarks: LinkdingBookmark[] = mockBookmarks.filter(bookmark => bookmark.unread);

export const mockBookmarkResponse: LinkdingResponse = {
  count: mockUnreadBookmarks.length,
  next: null,
  previous: null,
  results: mockUnreadBookmarks,
};

export const mockArchivedBookmarkResponse: LinkdingResponse = {
  count: mockArchivedBookmarks.length,
  next: null,
  previous: null,
  results: mockArchivedBookmarks,
};

export const mockAssets: LinkdingAsset[] = [
  {
    id: 1,
    asset_type: 'snapshot',
    content_type: 'text/html',
    display_name: 'HTML Snapshot',
    file_size: 45632,
    status: 'complete',
    date_created: '2024-01-01T10:15:00Z',
  },
  {
    id: 2,
    asset_type: 'pdf',
    content_type: 'application/pdf',
    display_name: 'PDF Version',
    file_size: 156789,
    status: 'complete',
    date_created: '2024-01-02T11:45:00Z',
  },
];

export const mockAssetResponse: LinkdingAssetResponse = {
  count: mockAssets.length,
  next: null,
  previous: null,
  results: mockAssets,
};

export const MOCK_URL = 'https://linkding.example.com';